services:
  rutracker-notifier:
    build:
      dockerfile: ./docker-build/apps/Dockerfile
      context: ./
    container_name: rutracker_bot
    restart: unless-stopped
    env_file:
      - ./src/.env
    volumes:
      - ./src:/src
      - rutracker_data:./src/data

volumes:
  rutracker_data: