services:
  rutracker-notifier:
    build:
      dockerfile: ./docker-build/apps/Dockerfile
      context: ./
    container_name: rutracker_bot
    restart: unless-stopped
    env_file:
      - ./src/.env
    volumes:
      # Монтируем весь проект в /app
      - ./:/app
      # ИЗОЛИРУЕМ виртуальное окружение контейнера от локальной машины:
      - /app/.venv
      # Volume для данных БД:
      - rutracker_data:/app/src/data

volumes:
  rutracker_data: